baseurl = "/"
languageCode = "en-us"
title = "Hot Currie"

# Preserve special characters in taxonomy names ("Gérard Depardieu" vs "Gerard Depardieu")
preserveTaxonomyNames =  true

[taxonomies]
  category = "categories"
  tag = "tags"
  cftag = "cftags"